# Generated by Django 4.1 on 2025-02-22 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='betaservistext',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Превью поста'),
        ),
    ]
