# Generated by Django 5.1.6 on 2025-05-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0008_category_bottom_alter_article_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='thumbnail',
            new_name='thumbnail_bottom',
        ),
    ]
