# Generated by Django 5.1.6 on 2025-05-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0009_rename_thumbnail_course_thumbnail_bottom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_bottom',
            new_name='CategoryBottom',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL категории'),
        ),
    ]
