# Generated by Django 5.1.6 on 2025-05-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0011_remove_course_price_remove_course_students_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='descp_full',
            field=models.TextField(max_length=255),
        ),
    ]
